the_clients/urls.py
from django.urls import re_path, path

from . import views


app_name = 'the_clients'
urlpatterns = [

     path("", views.list_clients, name="list"),
     path("<int:pk>", views.display_client, name="display"),
     path("add", views.add_client, name="add"),
     path("update/<int:pk>", views.update_client, name="update"),


]

the_clients/templates/the_clients/add.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Create new Client" %}{% endblock %}

{% block content %}
{% load crispy_forms_tags %}


<div class="container-fluid">
    <!-- LOGIN -->
    <div class="row mt-2">
        <div class="col">
            <div class="card">
                <div class="card-header"><Strong>{% trans "Create new Client" %}</Strong></div>

                <div class="card-body">
                    <form method="POST" onsubmit="show_processing_model()" action="" class="">
                        {% csrf_token %}
                        {{ add_form|crispy }}


                        <div class="row">
                            <div class="col">
                                <button class="btn btn-primary px-4" type="submit">{% trans "Create" %}
                                </button>
                            </div>

                        </div>


                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

the_clients/templates/the_clients/display.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Update Client" %}{% endblock %}

{% block content %}
{% load crispy_forms_tags %}


<div class="container-fluid">
    <!-- LOGIN -->
    <div class="row mt-2">
        <div class="col">
            <div class="card">
                <div class="card-header"><Strong>{% trans "Client"  %} "{{client.user}}"</Strong></div>

                <div class="card-body">
                    <table class="table table-responsive-sm table-hover   mb-0 w-100 d-block d-md-table">
                        <tbody>
                          
                            <tr>
                                <th scope="row">{% trans "Active" %}</th>
                                <td>{{client.active}}</td>
                            </tr>
                            <tr>
                                <th scope="row">{% trans "Access token" %}</th>
                                <td><textarea disabled rows="5" cols="100">{{client.token}}</textarea></td>
                            </tr>
                            {% comment %} <tr>
                                <th scope="row">{% trans "Refresh Token" %}</th>
                                <td><textarea disabled rows="5" cols="100">{{client.refresh_token}}</textarea></td>
                            </tr> {% endcomment %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

the_clients/templates/the_clients/list.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% block head_title %}{% trans "Clients" %}{% endblock %}

{% block content %}
{% load crispy_forms_tags %}


<div class="container-fluid">
    <!-- LOGIN -->
    <div class="row mt-2">
        <div class="col">
            <div class="card">
                <div class="card-header"><Strong>{% trans 'Clients' %}</Strong> <a href = "{% url 'the_clients:add' %}" class="btn btn-primary float-right">{% trans '+ Add new' %}</a> </div>
                <div class="card-body">
                    <table class="table table-responsive-sm table-hover table-outline mb-0 w-100 d-block d-md-table">
                        <thead class="thead-dark">
                        <tr>
                            <th  class="text-center">{% trans "User" %}</th>
                            <th  class="text-center">{% trans "Is Active" %}</th>
                            <th  class="text-center">{% trans "Options" %}</th>


                        </tr>
                        </thead>
                        <tbody>
                        {% for client in clients %}
                        <tr>
                            <td  class="text-center">
                                {{ client.user }}

                            </td >
                           
                            <td  class="text-center">

                                {% if client.active == True %}
                                <svg class="c-icon c-icon-lg">
                                    <use xlink:href="{{ STATIC_URL }}coreui/vendors/coreui/icons/svg/free.svg#cil-check-alt"></use>
                                </svg>
                                {% else %}
                                <svg class="c-icon c-icon-lg">
                                    <use xlink:href="{{ STATIC_URL }}coreui/vendors/coreui/icons/svg/free.svg#cil-x"></use>
                                </svg>
                                {% endif %}
                            </td>

                        

                            <td  class="text-center">

                                <a href = "{% url 'the_clients:update' pk=client.pk %}" class="">
                                    {% trans "Update" %}
                                </a> |
                                <a href="{{client.get_absolute_url}}" class="">
                                    {% trans "View" %} 
                                </a>
                            </td>
                        </tr>
                        {% empty %}
                        <tr >

                            <td  class="text-center" colspan="6"><p class="text-center">{% trans 'No Record Found.' %}</p></td>

                        </tr>

                        {% endfor %}
                        </tbody>
                    </table>
                    {% include "pagination.html" with paginator=clients %}



                </div>
            </div>
        </div>


    </div>
</div>
{% endblock %}

the_clients/templates/the_clients/update.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Update Client" %}{% endblock %}

{% block content %}
{% load crispy_forms_tags %}


<div class="container-fluid">
    <!-- LOGIN -->
    <div class="row mt-2">
        <div class="col">
            <div class="card">
                <div class="card-header"><Strong>{% trans "Update Client"  %} "{{client_to_update.user}}"</Strong></div>

                <div class="card-body">
                    <form method="POST" onsubmit="show_processing_model()" action="" class="">
                        {% csrf_token %}
                        {{ form|crispy }}


                        <div class="row">
                            <div class="col">
                                <button class="btn btn-primary px-4" type="submit">{% trans "Update" %}
                                </button>
                            </div>

                        </div>


                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}